from typing import List, Annotated
from typing_extensions import TypedDict
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableConfig
from langchain.agents import create_agent
from langchain_core.messages import AIMessage
from app.core.config import settings
from app.core.models import AgentState

from pydantic import BaseModel, Field

class ProductRecommendation(BaseModel):
    product_name: str = Field(description="The exact brand and name of the product.")
    product_image: str = Field(description="URL of the product image. Leave empty if unavailable.")
    description: str = Field(description="Brief description of the product.")
    price: str = Field(description="Price of the product.")
    ref: str = Field(description="URL of the product or store.")

class AgentOutputFormat(BaseModel):
    recommendations: List[ProductRecommendation] = Field(description="List of exactly 3 recommended products based on the search")

class ShoppingSearchNode:
    def __init__(self, llm, tavily_tool=None):
        self.llm = llm
        self.tavily_tool = tavily_tool

    async def __call__(self, state: AgentState, config: RunnableConfig):
        language = state.get("language", "English")
        explanation = state.get("explanation", "No explanation provided.")

        # Derive the expected JSON structure dynamically from Pydantic model
        import json
        json_schema_text = json.dumps(AgentOutputFormat.model_json_schema(), indent=2)

        system_prompt = f"""<role>Medical Product Recommender</role>
<language>{language}</language>

<goal>List current product name, image, description, price, and url that can help the patient's condition and return them in a structured JSON format.</goal>

<context>
The patient recently received this medical explanation:
{explanation}
</context>

<task>
  1. You MUST use your search tool (`tavily_tool`) to find exactly 3 REAL topical treatments, medications, or skincare products for this condition. Prioritize Watsons, Sephora, or Boots.
  2. Extract the exact product name, product image URL, description, price, and the real product URL.
  3. You MUST return ONLY a valid JSON object matching the schema below.
</task>

<json_schema>
{json_schema_text}
</json_schema>

<constraints>
  - CRITICAL: Respond in {language} ONLY. Do NOT add translations in brackets.
  - NEGATIVE: Do NOT greet the user or start with "Okay", "I understand", "Got it", "Sure", or any filler.
  - NEGATIVE: Do NOT say "Thank you" or any closing statement.
  - NEGATIVE: Do NOT repeat or acknowledge the user's previous message.
  - NEGATIVE: Do NOT translate anything inside brackets.
  - CRITICAL: You MUST use the search tool to find real products. DO NOT GUESS.
  - CRITICAL: Return ONLY real products found online. DO NOT hallucinate URLs like `example.com`.
  - CRITICAL: If you cannot find a real image URL or product link from the search result, leave it blank rather than making one up.
  - Output exactly 3 results.
  - No robot talk. Direct and warm tone.
  - Style: Concise, connected, and smart.
  - Keep it to 1-2 sentences max, followed by a short product list if applicable.
  - You MUST return the JSON block. Do not include any other text outside the JSON.
</constraints>"""

        tools = [self.tavily_tool] if self.tavily_tool else []
        
        agent = create_agent(
            model=self.llm,
            tools=tools,
            system_prompt=system_prompt,
            response_format=AgentOutputFormat
        )
        
        try:
            response = await agent.ainvoke({"messages": state["messages"]}, config=config)
            print("shopping_search: type of response", type(response))
            print(response)
            
            # # Defensive parsing: handle Pydantic model or dict
            # if isinstance(response, AgentOutputFormat):
            #     recommendations = [item.model_dump() for item in response.recommendations]
            # elif isinstance(response, dict):
            #     recommendations = response.get("recommendations", [])
            # else:
            #     # If it returned a string or AIMessage content instead, try to extract JSON
            #     import json
            #     import re
            #     content = getattr(response, 'content', str(response))
            #     # Simple regex to find content between { }
            #     match = re.search(r'(\{.*\})', content, re.DOTALL)
            #     if match:
            #         parsed = json.loads(match.group(1))
            #         recommendations = parsed.get("recommendations", [])
            #     else:
            #         recommendations = []
            
            # Extract the raw JSON string generated by the agent
            if isinstance(response, dict) and "messages" in response and response["messages"]:
                last_message = response["messages"][-1]
                recommendations = getattr(last_message, "content", str(last_message))
            else:
                recommendations = str(response)
            
            # Formulate a nice chat message acknowledging the products
            text_response = AIMessage(content=f"Here are some recommended products for you:")

        except Exception as e:
            print(f"Error in ShoppingSearchNode: {e}")
            recommendations = []
            text_response = AIMessage(content="I'm sorry, I couldn't find any products at the moment.")

        return {
            "messages": [text_response],
            "search_results": recommendations,
        }
